#!/bin/bash
# This script reads /etc/passwd and displays username, user id and home directory

while IFS=: read -r username _ userid _ _ homedir _
do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homedir"
    echo ""
done < /etc/passwd
