#!/usr/bin/env bash
# This script reads /etc/passwd and displays username, user id and home directory

while IFS=: read -r username _ userid _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd
